# Generated by Django 3.2 on 2022-11-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=180)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('website', models.CharField(max_length=180)),
                ('status', models.CharField(choices=[('', 'select'), ('sole_propriatorship', 'Sole Propriatorship'), ('private_limited_company', 'Private Limited Company'), ('partnership', 'Partnership'), ('social_enterprise', 'Social Enterprise'), ('NGO', 'NGO'), ('other', 'Other')], max_length=180)),
                ('activity', models.CharField(max_length=180)),
                ('stage', models.CharField(max_length=180)),
                ('company_summary', models.TextField()),
                ('management_summary', models.TextField()),
                ('financial_information', models.CharField(max_length=180)),
                ('capital', models.CharField(max_length=180)),
                ('capital_type', models.CharField(max_length=180)),
                ('venture', models.CharField(max_length=180)),
                ('reason', models.CharField(max_length=180)),
                ('current_source', models.CharField(max_length=180)),
                ('pitch_deck', models.FileField(upload_to='')),
            ],
        ),
    ]
